all:
	@echo Nothing to be made.

clean:
	rm -f *~ *.o *.d
	rm -f ./wpa_supplicant_8_lib/*~ ./wpa_supplicant_8_lib/*.o ./wpa_supplicant_8_lib/*.d
	rm -f build.wpa_supplicant build.hostapd

install:
	@echo Nothing to be made.
